-- MySQL Script generated by MySQL Workbench
-- 06/20/18 23:05:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema voting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voting` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `voting` ;

-- -----------------------------------------------------
-- Table `voting`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting`.`elector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting`.`elector` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `surnames` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `id_document` VARCHAR(50) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_elector_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_elector_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `voting`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `elector_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC),
  INDEX `fk_user_elector_idx` (`elector_id` ASC),
  CONSTRAINT `fk_user_elector`
    FOREIGN KEY (`elector_id`)
    REFERENCES `voting`.`elector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_area_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_area_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `voting`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_department_area1_idx` (`area_id` ASC),
  CONSTRAINT `fk_department_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `voting`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting`.`committee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting`.`committee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_committee_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_committee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `voting`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting`.`candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting`.`candidate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `committee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidate_committee1_idx` (`committee_id` ASC),
  CONSTRAINT `fk_candidate_committee1`
    FOREIGN KEY (`committee_id`)
    REFERENCES `voting`.`committee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting`.`vote` (
  `elector_id` INT NOT NULL,
  `candidate_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`elector_id`, `candidate_id`),
  INDEX `fk_elector_has_candidate_candidate1_idx` (`candidate_id` ASC),
  INDEX `fk_elector_has_candidate_elector1_idx` (`elector_id` ASC),
  CONSTRAINT `fk_elector_has_candidate_elector1`
    FOREIGN KEY (`elector_id`)
    REFERENCES `voting`.`elector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_elector_has_candidate_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `voting`.`candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
